### ISSUE TITLE
Unable to grab an email 

### ISSUE THREAD

**Issue by Daniel3356** [TufayelLUS/LinkedIn-Email-Scraper#1]
Hi I'm using Python 3.9.2 and I install the pre-request with pip, I insert my LinkedIn credentials but I'm getting:
['desktop-cm-upsell-facepile@2x.png', 'new-poster-desktop-modal-image@2x.png'].
Instead of the profile email address. 

Thanks for helping me or fixing the bug.

**Comment by TufayelLUS** [comment]
Hi, the regular expression used in this code is not fully efficient enough to filter image formats yet but as long as there exists correct image that is visible and accessible by the code, it will include that.
